default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: azbooky_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  template: template0

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
